Refactor Bash scripts to follow modern conventions

diff --git a/script/lint b/script/lint
--- a/script/lint
+++ b/script/lint
@@ -1,9 +1,23 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-cd "${BASH_SOURCE%/*}" || exit
+# Exit on failure, and treat expansion of unset variables as an error.
+set -eu
 
-echo "Linting package..."
-$(npm bin)/standard --verbose "../lib/**/*.js" | $(npm bin)/snazzy
+_lint() {
+  local npm_bin=$( npm bin )
+  local paths="$1"
 
-echo "Linting package specs..."
-$(npm bin)/standard --verbose "../spec/**/*.js" | $(npm bin)/snazzy
+  "$npm_bin/standard" --verbose "$paths" | "$npm_bin/snazzy"
+}
+
+main() {
+  local script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
+  local source_dir=$( dirname "$script_dir" )
+
+  local -i status=0
+  echo "Linting package..." && _lint "$source_dir/lib/**/*.js" || status=$?
+  echo "Linting package specs..." && _lint "$source_dir/spec/**/*.js" || status=$?
+  return $status
+}
+
+main "$@"
